FROM python:slim
WORKDIR /api
COPY ../../requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 5000
CMD ["gunicorn", "src.api.server:app" ,"--bind=0.0.0.0:5000", "--workers=2", "--reload", "--log-level", "debug" ]

