version: '3.1'
services:

  postgresql:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=ddorcak
      - POSTGRES_PASSWORD=ddorcak
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"

  flask-server:
    volumes:
      - '/home/dorcak/Skola/Diplomka/fontree/src:/api/src'
    build:
      dockerfile: ./docker/flask/DOCKERFILE
      context:  ..
    ports:
      - '5000:5000'

volumes:
  db:
    driver: local
